services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mlflow_poc_app
    ports:
      - "8000:8000"
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /code/gcloud-service-account.json
      PROJECT_ID: llm-services-450013
      LOCATION: us-central1
      MLFLOW_TRACKING_URI: http://mlflow:5000     
    volumes:
      - .:/code
    depends_on:
      mlflow:
        condition: service_started
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  mlflow:
    container_name: mlflow
    image: ghcr.io/mlflow/mlflow
    command: >
      mlflow server
      --backend-store-uri sqlite:////mlflow/mlflow.db
      --default-artifact-root /mlflow/artifacts
      --host 0.0.0.0
      --port 5000
      --allowed-hosts "*"
      --cors-allowed-origins "*"
    environment:
      MLFLOW_SERVE_ARTIFACTS: "true"
      MLFLOW_ALLOWED_HOSTS: "*"
    ports:
      - "5050:5000"
    volumes:
      - ./mlflow_data:/mlflow

